INSERT INTO industry (name) VALUES
('INFORMATION_TECHNOLOGY'),
('BANKING_AND_FINANCE'),
('GOVERNMENT'),
('HEALTHCARE'),
('EDUCATION'),
('MANUFACTURING'),
('AUTOMOBILE'),
('TELECOMMUNICATION'),
('RETAIL'),
('HOSPITALITY'),
('CONSTRUCTION'),
('REAL_ESTATE'),
('TRANSPORTATION'),
('LOGISTICS'),
('AGRICULTURE'),
('FREELANCE'),
('STARTUP');


INSERT INTO property_type (name) VALUES
('RESIDENTIAL'),
('APARTMENT'),
('VILLA'),
('PLOT'),
('COMMERCIAL'),
('INDUSTRIAL'),
('AGRICULTURAL_LAND');


INSERT INTO loan_purpose (name) VALUES
('HOME_PURCHASE'),
('HOME_CONSTRUCTION'),
('HOME_RENOVATION'),
('VEHICLE_PURCHASE'),
('EDUCATION'),
('BUSINESS_EXPANSION'),
('WORKING_CAPITAL'),
('MEDICAL_EMERGENCY'),
('PERSONAL_EXPENSE'),
('DEBT_CONSOLIDATION'),
('VACATION'),
('WEDDING');



